### ISSUE TITLE
module 'dbt.flags' has no attribute 'SINGLE_THREADED_WEBSERVER'

### ISSUE THREAD

**Issue by varun-dc** [dbt-labs/dbt-rpc#58]
Hi,

We're running dbt-rpc and noticing after upgrading to 1.0.0b2 and dbt-rpc we're getting exceptions on start up,
```
$ dbt-rpc --log-format text serve --profile dc_dbt_int_snowflake --target dev --port 8581
Running with dbt=1.0.0-b2
* Deprecation Warning: The `source-paths` config has been deprecated in favor of
`model-paths`. Please update your `dbt_project.yml` configuration to reflect
this change.
Encountered an error:
module 'dbt.flags' has no attribute 'SINGLE_THREADED_WEBSERVER'
```
We can disregard the deprecation warning here.

The following versions are installed,
```
$ pip list | grep dbt
dbt-core                   1.0.0b2                                                                                                                                                                                          
dbt-extractor              0.4.0                                                                                                                                                                                            
dbt-rpc                    0.1.0                                                                                                                                                                                            
dbt-snowflake              0.21.0
```

Doing some debugging, the following changes appear to fix the immediate issue (I don't know what effect these changes have on everything else in dbt-rpc)

`./venv/lib/python3.9/site-packages/dbt_rpc/rpc/task_handler.py`,
```
    @property
    def _single_threaded(self):
        return bool(
            self.task.args.single_threaded or
            True #  dbt.flags.SINGLE_THREADED_HANDLER
        )
```

`./venv/lib/python3.9/site-packages/dbt_rpc/rpc/task_manager.py`,
```
    def single_threaded(self):
        return (
            True # flags.SINGLE_THREADED_WEBSERVER
            or self.args.single_threaded
        )

```

**Comment by jtcohen6** [comment]
@varun-dc Sorry for the confusion! This one is on me—we made a change in `dbt-core==1.0.0b2`, without properly coordinating an update here at the same time.

We just merged a fix for this (#56), and we're about to bump the version (#57) and cut a new release.

**Comment by varun-dc** [comment]
Thanks @jtcohen6. I'll try installing from source.

**Comment by jtcohen6** [comment]
Thanks for testing @varun-dc! Release is live
